### ISSUE TITLE
Check if is full screen for everyone?

### ISSUE THREAD

**Issue by WhoAmI125** [WhoAmI125/RoomEscape#7]
Could everyone check if current rooms show up as full screen? My computer seems not. We need to check if everyone does not look correct (then it is error) or if only some of us, then we need to think of new way to solve.

![image](https://user-images.githubusercontent.com/87934953/168482888-f37d0467-74c1-4aea-aa11-e9f457795ef6.png)

![image](https://user-images.githubusercontent.com/87934953/168482902-9a61359b-2f85-4379-a0f0-83aeffe20064.png)

**Comment by user13571** [comment]
![image](https://user-images.githubusercontent.com/100356286/168507860-85584966-daec-4642-810a-43c56c83992b.png)

**Comment by user13571** [comment]
It's because the size is different for each computer and screen setting.
To make fullscreen, the initial width must be set to the screen size (set to fixed) and the size and position of the object must be set to a percentage setting

**Comment by user13571** [comment]
Also, if we set the width to the screen size, I think it would be easier to make the height a fixed aspect ratio considering the width even if there is a bottom margin

**Comment by user13571** [comment]
I added fullscreen branch.
I only fixed main room size now, and position and object size will be changed later.

**Comment by WhoAmI125** [comment]
> I added fullscreen branch. I only fixed main room size now, and position and object size will be changed later.

Sure let me try to fix the door position amd check if crashes or not

**Comment by WhoAmI125** [comment]
@user13571 I fixed the ratio and screen size could you check if it is still full screen on your computer?

**Comment by coolfunjoon21** [comment]
[](url
<img width="1440" alt="스크린샷 2022-05-16 오후 1 36 45" src="https://user-images.githubusercontent.com/80045676/168520745-e31ce94e-d074-466c-aaff-ae708d945a75.png">
)

Width is fixed, but height is not fixed yet.
Photo image: full screen zoom 100%

**Comment by user13571** [comment]
![image](https://user-images.githubusercontent.com/100356286/168522932-9abac032-206a-402d-a19d-ed9e645faa91.png)
Height is overflowing in my environment.

**Comment by WhoAmI125** [comment]
Okay maybe it might because I added extra padding-bottom for 16:9 ratio.
I removed the line and added percentage to the door could you check?

The prob with percentage is that if you change screen % (resize the tab) the location is not stable.

**Comment by user13571** [comment]
![image](https://user-images.githubusercontent.com/100356286/168525061-acd19adf-129c-486f-bb9a-dd94eef5fa71.png)
![image](https://user-images.githubusercontent.com/100356286/168525099-87445a05-1c4d-4529-b1d8-c0a28a69099c.png)
Maybe we should fix screen size after initializing?

**Comment by coolfunjoon21** [comment]
https://user-images.githubusercontent.com/80045676/168530896-841e3842-1a65-436a-8e76-70342753af27.mp4

Here's how it looks

**Comment by WhoAmI125** [comment]
> DEMO.mp4 
> Here's how it looks

Thanks I think we can first work on everything else and then move on to this next. I will leave the issue open
